Import("*")
env.Append(CPPPATH="#libs/driver/include/sys-%s" % args["system"])
lib = env.KengeLibrary("driver", LIBS=["c"])
Return("lib")
"""
import os

public_headers = ["#libs/driver/include", "#libs/driver/include/sys-%s" % args["system"]]

if args["system"] in ["iguana"]:
    cpppath = env.libs["l4"][0]
else:
    cpppath = ""

libdriver = env.StaticLibrary('driver',
                              src_glob("src/*.c") + src_glob("src/sys-%s/*.c" % args["system"]),
                              CPPPATH=["src", "include",  "include/sys-%s" % args["system"]] +  env.libs["c"][0] + [cpppath])

if scons_version <= (0, 95):
    libdriver = [libdriver]

libdriver = libdriver[0]

lib = (public_headers, libdriver, "#" + os.path.dirname(libdriver.path), None, [])
"""

