#ifndef _LIBS_IGUANA_INTERFACE_UUIDS_H
#define _LIBS_IGUANA_INTERFACE_UUIDS_H
static const int INTERFACE_IGUANA_EX_UUID = 21;
static const int INTERFACE_IGUANA_PD_UUID = 22;
static const int INTERFACE_IGUANA_EAS_UUID = 23;
static const int INTERFACE_IGUANA_THREAD_UUID = 24;
static const int INTERFACE_IGUANA_HARDWARE_UUID = 25;
static const int INTERFACE_IGUANA_MEMSECTION_UUID = 26;
static const int INTERFACE_IGUANA_SESSION_UUID = 27;
static const int INTERFACE_IGUANA_DEBUG_UUID = 28;
static const int INTERFACE_IGUANA_QUOTA_UUID = 29;
#endif
