/*
 * @NICTA_MODIFICATIONS_START@
 * 
 * This source code is licensed under Apple Public Source License Version 2.0.
 * Portions copyright Apple Computer, Inc.
 * Portions copyright National ICT Australia.
 *
 * All rights reserved.
 *
 * This code was modified 2006-06-20.
 *
 * @NICTA_MODIFICATIONS_END@
 */
/*
 * Copyright (c) 2001-2005 Apple Computer, Inc. All rights reserved.
 *
 * @APPLE_LICENSE_HEADER_START@
 *
 * The contents of this file constitute Original Code as defined in and
 * are subject to the Apple Public Source License Version 2.0 (the
 * "License").  You may not use this file except in compliance with the
 * License.  Please obtain a copy of the License at
 * http://www.apple.com/publicsource and read it before using this file.
 *
 * This Original Code and all software distributed under the License are
 * distributed on an "AS IS" basis, WITHOUT WARRANTY OF ANY KIND, EITHER
 * EXPRESS OR IMPLIED, AND APPLE HEREBY DISCLAIMS ALL SUCH WARRANTIES,
 * INCLUDING WITHOUT LIMITATION, ANY WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE OR NON-INFRINGEMENT.  Please see the
 * License for the specific language governing rights and limitations
 * under the License.
 *
 * @APPLE_LICENSE_HEADER_END@
 */
/*
  Automatically generated by 'make config' -- don't edit!

  Actually, for Mac OS X this was hand edited :-)

*/
#ifndef _PCMCIA_CONFIG_H
#define _PCMCIA_CONFIG_H

#define AUTOCONF_INCLUDED
#define __IN_PCMCIA_PACKAGE__

#define __MACOSX__ 1
#undef	LINUX				//macosx
#undef	PREFIX
#define CC "gcc"
#define LD "ld"
#define KFLAGS ""
#define UFLAGS ""
#define PCDEBUG ""
#undef	USE_PM
#undef 	UNSAFE_TOOLS
#define	CONFIG_CARDBUS 1
#define CONFIG_PNP_BIOS 1
#undef	MODDIR
#undef	HAVE_MEMRESERVE 1

/* Options from current kernel */
#undef	CONFIG_MODULES 1
#define	CONFIG_SMP 1
#define CONFIG_PCI 1
#define CONFIG_PCI_QUIRKS 1
#undef	CONFIG_PM 1
#define CONFIG_SCSI 1
#undef  CONFIG_IEEE1394
#define CONFIG_INET 1
#define CONFIG_NET_PCMCIA_RADIO 1
#define CONFIG_TR 1
#undef  CONFIG_NET_FASTROUTE
#undef  CONFIG_NET_DIVERT
#define CONFIG_MODVERSIONS 1
#define CONFIG_X86_L1_CACHE_BYTES 32
#define CONFIG_X86_L1_CACHE_SHIFT 5
#define CONFIG_PROC_FS 1
#define CONFIG_1GB 1
#undef  CONFIG_2GB
#undef  CONFIG_3GB
#define ARCH "ppc"
#define HOST_ARCH "ppc"
#define AFLAGS ""
#undef	CONFIG_ISA			//macosx

#undef	HAS_PROC_BUS			//macosx
#undef	SYSV_INIT
#undef  HAS_FORMS

#endif /* _PCMCIA_CONFIG_H */
