Import("*")

srcList=[]
srcList += src_glob("../xnuglue/src/shared/netbuf.c")
srcList += src_glob("../xnuglue/src/shared/lock.S")
# srcList += src_glob("../xnuglue/src/shared/fb.c")

lib = env.MyLibrary("iokitcli", 
	CCFLAGS=["-DNOTFB31=0", 
	"-D__pic__",
	"-DDEBUG=0",
	"-static",
	"-DLP64_DEBUG=0",
	"-DDIAGNOSTIC=1",
	"-DIOASSERT=0",
	"-DTASK_SWAPPER=0",
	"-DBLUE_DEBUG=0",
	"-DTYPE_BOOL=0",
	"-DSENDFILE=0", 
	"-DCOMPAT_43_TTY=0",
	"-DMACH_KERNEL_PRIVATE", 
	"-DMACH_ASSERT", 
	"-DKERNEL", 
	"-D__APPLE_API_UNSTABLE", 
	"-DPRIVATE=1", 
	"-DMACH_DEBUG=0", 
	"-DMACH_LDEBUG=0", 
	"-DXNU_KERNEL_PRIVATE=1", 
	"-DKERNEL_PRIVATE", 
	"-D__BIG_ENDIAN__=0", 
	"-D__LITTLE_ENDIAN__=1", 
	"-DL4IOKIT", 
	"-D__APPLE__=1", 
	"-DBSD_KERNEL_PRIVATE=1", 
	"-DBSD_BUILD=1",
	"-fno-strict-aliasing"], 
	CXXFLAGS=["-DPRIVATE=1", 
	"-DXNU_KERNEL_PRIVATE=1", 
	"-DKERNEL_PRIVATE",  
	"-D__LITTLE_ENDIAN__=1", 
	"-DL4IOKIT",
	"-fno-strict-aliasing"], 
	CPPPATH=["#libs/xnuglue/xnu_include/include", 
	"#libs/xnuglue/xnu_iclude/include/bsd", 
	"#libs/xnuglue/xnu_include/include/EXTERNAL_HEADERS", 
	"#libs/xnuglue/xnu_include/include/osfmk", 
	"#libs/xnuglue/xnu_include/include/pexpert", 
	"#libs/xnuglue/xnu_include/include/bsd", 
	"#libs/libkern",  
	"#libs/iokit",
        "#libs/pants1",
        "#libs/xnuglue/include", # ceg
        "#libs/pants2",
	"#libs/xnuglue/xnu_include"], 
	source=srcList,
	LIBS=[])

Return("lib")
