# Stuff for testing
Import('tests_env')
tests_env.TestLibrary('test_libs_binary_tree', 'libs/binary_tree/', ['src/*.c', 'test/*.c'])

# Stuff for regular Iguana build.
Import("env")
lib = env.MyLibrary("binary_tree", LIBS=["c"])
Return("lib")
